### PR TITLE
Adding mapping for postgres13

### PR DESCRIPTION
**Pull request by MacdonEm**
Updating downstream with postgres13 integration.

### CODE REVIEW

**Comment by schmidtd** [comment]
The version actually in quay is this:
postgresql-13@sha256:a9a53f6ca6e73f9baeb15b3c0a596825ef84bd5d775e693ec26a85031ab46909

**Comment by MacdonEm** [comment]
Whoops, my bad. I've updated the changes to the correct sha.

**Review by schmidtd — COMMENTED** [review]
T'would be cool if the specs had suffixes like `-12` and `-13` to distinguish among them, and maybe some updated chatter in the comments too

**Comment by MacdonEm** [comment]
That would be pretty cool, and wouldn't you know it, they _are_ named that way now @schmidtd

**Review by schmidtd — APPROVED** [review]
LGTM

**Pull request merged**
